### ISSUE TITLE
JSON does not have functions.

### ISSUE THREAD

**Issue by ehartford** [yusufnb/verify-json#1]
JSON does not have functions.  

    func      : _.isFunction,
    f         : _.isFunction,    // alias for func

Is this a JavaScript object validator, or a JSON validator?

**Comment by Miladiir** [comment]
Probably a validator for objects that are parsed from JSON. The JSON and JS objects are confused often for each other in this context.

**Comment by yusufnb** [comment]
I agree. It does not apply to JSON. This validator is mainly to validate the custom validators recursively.
